import { connect } from 'cloudflare:sockets';
const T = 'f781f727-7127-49f7-9910-228e81519e90';
const FA = 'ProxyIP.cmliussss.net';
const FP = '443';
const CU = '';                      // config-manager-kv.js 的部署地址（如 https://cfg.example.com）
const AS = 'snip-sync-2024';        // 与 config-manager-kv.js 中的密钥保持一致
const CD = 60000;                   // socks 配置缓存时长(ms)，0 = 每次连接都回管理端取
function genSocksKey(idx) { const src = T + '-socks-' + idx, chars = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789'; let hash = 0; for (let i = 0; i < src.length; i++) { hash = ((hash << 5) - hash) + src.charCodeAt(i); hash = hash & hash; } let key = ''; for (let i = 0; i < 8; i++) { hash = Math.abs((hash * 1103515245 + 12345) & 0x7fffffff); key += chars[hash % chars.length]; } return key; }
const E1 = atob('aW52YWxpZCBkYXRh'), E2 = atob('aW52YWxpZCB1c2Vy'), E3 = atob('Y29tbWFuZCBpcyBub3Qgc3VwcG9ydGVk'), E4 = atob('VURQIHByb3h5IG9ubHkgZW5hYmxlIGZvciBETlMgd2hpY2ggaXMgcG9ydCA1Mw=='), E5 = atob('aW52YWxpZCBhZGRyZXNzVHlwZQ=='), E6 = atob('YWRkcmVzc1ZhbHVlIGlzIGVtcHR5'), E7 = atob('d2ViU29ja2V0LmVhZHlTdGF0ZSBpcyBub3Qgb3Blbg=='), E8 = atob('U3RyaW5naWZpZWQgaWRlbnRpZmllciBpcyBpbnZhbGlk'), E9 = atob('SW52YWxpZCBTT0NLUyBhZGRyZXNzIGZvcm1hdA=='), EA = atob('bm8gYWNjZXB0YWJsZSBtZXRob2Rz'), EB = atob('c29ja3Mgc2VydmVyIG5lZWRzIGF1dGg='), EC = atob('ZmFpbCB0byBhdXRoIHNvY2tzIHNlcnZlcg=='), ED = atob('ZmFpbCB0byBvcGVuIHNvY2tzIGNvbm5lY3Rpb24=');
const A1 = 1, A2 = 2, A3 = 3;
const scC = new Map();
async function gSocks(idx) { if (!CU || !AS) return null; const now = Date.now(), h = scC.get(idx); if (h && now - h.t < CD) return h.c; try { const r = await fetch(`${CU.replace(/\/+$/, '')}/api/socks?index=${idx}&key=${AS}`, { headers: { 'User-Agent': 'VLESS-Worker' } }); if (!r.ok) return null; const d = await r.json(), c = d.config || null; if (c) scC.set(idx, { c, t: now }); return c; } catch (e) { return null; } }
export default { async fetch(request, env, ctx) { try { if (request.headers.get('Upgrade') === 'websocket') return await hWs(request); return new Response('Not Found', { status: 404 }); } catch (err) { return new Response(err.toString(), { status: 500 }); } } };
async function hWs(request) { const url = new URL(request.url), sP = url.searchParams.get('socks'), sI = sP !== null ? parseInt(sP) : -1; let pSC = {}, iSE = false, fbS = false; if (sI >= 0) { const expKey = genSocksKey(sI); let hasKey = false; for (const k of url.searchParams.keys()) { if (k === expKey && url.searchParams.get(k) === '') { hasKey = true; break; } } if (!hasKey) return new Response('Unauthorized', { status: 401 }); const realConfig = await gSocks(sI); if (!realConfig) return new Response('SOCKS config not found', { status: 502 }); try { pSC = pS5(realConfig); } catch (e) { return new Response('Invalid SOCKS config', { status: 500 }); } if (url.searchParams.has('fb')) fbS = true; else iSE = true; } const wsPair = new WebSocketPair(), [cS, sS] = Object.values(wsPair); sS.accept(); let rcw = { socket: null }, isDns = false; const ed = request.headers.get('sec-websocket-protocol') || '', rd = mRS(sS, ed); rd.pipeTo(new WritableStream({ async write(chunk) { if (isDns) return await fUDP(chunk, sS, null); if (rcw.socket) { const w = rcw.socket.writable.getWriter(); await w.write(chunk); w.releaseLock(); return; } const { hasError, message, addressType, port, hostname, rawIndex, version, isUDP } = pPkt(chunk, T); if (hasError) throw new Error(message); if (isUDP) { if (port === 53) isDns = true; else throw new Error(E4); } const rh = new Uint8Array([version[0], 0]), rD = chunk.slice(rawIndex); if (isDns) return fUDP(rD, sS, rh); await fTCP(addressType, hostname, port, rD, sS, rh, rcw, iSE, pSC, fbS); } })).catch((e) => { }); return new Response(null, { status: 101, webSocket: cS }); }
async function fTCP(aT, host, pN, rD, ws, rh, rcw, iSE, pSC, fbS) { async function cAS(addr, port) { const rS = iSE ? await eSocks(aT, addr, port, pSC) : connect({ hostname: addr, port: port }), w = rS.writable.getWriter(); await w.write(rD); w.releaseLock(); return rS; } async function rC() { if (fbS) { const nS = await eSocks(aT, host, pN, pSC); const nW = nS.writable.getWriter(); await nW.write(rD); nW.releaseLock(); rcw.socket = nS; nS.closed.catch(() => { }).finally(() => cSock(ws)); cStr(nS, ws, rh, null); return; } const useProxy = FA && FA.trim(); if (!useProxy) { cSock(ws); return; } const nS = iSE ? await eSocks(aT, FA, parseInt(FP, 10) || 443, pSC) : connect({ hostname: FA, port: parseInt(FP, 10) || 443 }); const nW = nS.writable.getWriter(); await nW.write(rD); nW.releaseLock(); rcw.socket = nS; nS.closed.catch(() => { }).finally(() => cSock(ws)); cStr(nS, ws, rh, null); } try { const iS = await cAS(host, pN); rcw.socket = iS; cStr(iS, ws, rh, rC); } catch (e) { try { await rC(); } catch (err) { cSock(ws); } } }
function pPkt(chunk, token) { if (chunk.byteLength < 24) return { hasError: true, message: E1 }; const ver = new Uint8Array(chunk.slice(0, 1)); if (fID(new Uint8Array(chunk.slice(1, 17))) !== token) return { hasError: true, message: E2 }; const oL = new Uint8Array(chunk.slice(17, 18))[0], cmd = new Uint8Array(chunk.slice(18 + oL, 19 + oL))[0]; let isUDP = false; if (cmd === 1) { } else if (cmd === 2) { isUDP = true; } else return { hasError: true, message: E3 }; const pI = 19 + oL, port = new DataView(chunk.slice(pI, pI + 2)).getUint16(0); let aI = pI + 2, aL = 0, aVI = aI + 1, hn = ''; const aT = new Uint8Array(chunk.slice(aI, aVI))[0]; switch (aT) { case A1: aL = 4; hn = new Uint8Array(chunk.slice(aVI, aVI + aL)).join('.'); break; case A2: aL = new Uint8Array(chunk.slice(aVI, aVI + 1))[0]; aVI += 1; hn = new TextDecoder().decode(chunk.slice(aVI, aVI + aL)); break; case A3: aL = 16; const ipv6 = [], iv = new DataView(chunk.slice(aVI, aVI + aL)); for (let i = 0; i < 8; i++) ipv6.push(iv.getUint16(i * 2).toString(16)); hn = ipv6.join(':'); break; default: return { hasError: true, message: `${E5}: ${aT}` }; } if (!hn) return { hasError: true, message: `${E6}: ${aT}` }; return { hasError: false, addressType: aT, port, hostname: hn, isUDP, rawIndex: aVI + aL, version: ver }; }
function mRS(socket, edH) { let c = false; return new ReadableStream({ start(ctrl) { socket.addEventListener('message', (e) => { if (!c) ctrl.enqueue(e.data); }); socket.addEventListener('close', () => { if (!c) { cSock(socket); ctrl.close(); } }); socket.addEventListener('error', (e) => ctrl.error(e)); const { earlyData, error } = b64A(edH); if (error) ctrl.error(error); else if (earlyData) ctrl.enqueue(earlyData); }, cancel() { c = true; cSock(socket); } }); }
async function cStr(rS, wS, hD, rF) { let h = hD, hsDt = false, hasFailed = false; await rS.readable.pipeTo(new WritableStream({ async write(chunk, ctrl) { hsDt = true; if (wS.readyState !== 1) ctrl.error(E7); if (h) { wS.send(await new Blob([h, chunk]).arrayBuffer()); h = null; } else wS.send(chunk); }, abort(r) { hasFailed = true; } })).catch((e) => { hasFailed = true; cSock(wS); }); if ((!hsDt || hasFailed) && rF) { try { await rF(); } catch (e) { cSock(wS); } } }
async function fUDP(uC, wS, rH) { try { const tS = connect({ hostname: '8.8.4.4', port: 53 }); let vH = rH; const w = tS.writable.getWriter(); await w.write(uC); w.releaseLock(); await tS.readable.pipeTo(new WritableStream({ async write(chunk) { if (wS.readyState === 1) { if (vH) { wS.send(await new Blob([vH, chunk]).arrayBuffer()); vH = null; } else wS.send(chunk); } } })); } catch (e) { } }
async function eSocks(aT, addr, port, pSC) { const { username, password, hostname, socksPort } = pSC, s = connect({ hostname, port: socksPort }), w = s.writable.getWriter(); await w.write(new Uint8Array(username ? [5, 2, 0, 2] : [5, 1, 0])); const r = s.readable.getReader(); let res = (await r.read()).value; if (res[0] !== 5 || res[1] === 255) throw new Error(EA); if (res[1] === 2) { if (!username || !password) throw new Error(EB); const enc = new TextEncoder(), aR = new Uint8Array([1, username.length, ...enc.encode(username), password.length, ...enc.encode(password)]); await w.write(aR); res = (await r.read()).value; if (res[0] !== 1 || res[1] !== 0) throw new Error(EC); } const enc = new TextEncoder(); let DA; switch (aT) { case A1: DA = new Uint8Array([1, ...addr.split('.').map(Number)]); break; case A2: DA = new Uint8Array([3, addr.length, ...enc.encode(addr)]); break; case A3: DA = new Uint8Array([4, ...addr.split(':').flatMap(x => [parseInt(x.slice(0, 2), 16), parseInt(x.slice(2), 16)])]); break; default: throw new Error(E5); } await w.write(new Uint8Array([5, 1, 0, ...DA, port >> 8, port & 255])); res = (await r.read()).value; if (res[1] !== 0) throw new Error(ED); w.releaseLock(); r.releaseLock(); return s; }
function pS5(s) { let u = '', p = '', h, pt; const ai = s.lastIndexOf('@'); if (ai > 0) { const ap = s.substring(0, ai), hp = s.substring(ai + 1), ci = ap.indexOf(':'); if (ci > 0) { u = ap.substring(0, ci); p = ap.substring(ci + 1); } const lc = hp.lastIndexOf(':'); if (lc > 0) { h = hp.substring(0, lc); pt = Number(hp.substring(lc + 1)); } else { h = hp; pt = 1080; } } else { const lc = s.lastIndexOf(':'); if (lc > 0) { h = s.substring(0, lc); pt = Number(s.substring(lc + 1)); } else { h = s; pt = 1080; } } if (isNaN(pt)) throw new Error(E9); return { username: u, password: p, hostname: h, socksPort: pt }; }
function b64A(b) { if (!b) return { error: null }; try { b = b.replace(/-/g, '+').replace(/_/g, '/'); return { earlyData: Uint8Array.from(atob(b), (c) => c.charCodeAt(0)).buffer, error: null }; } catch (e) { return { error: e }; } }
function isVF(uuid) { return /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(uuid); }
function cSock(s) { try { if (s.readyState === 1 || s.readyState === 2) s.close(); } catch (e) { } }
const hT = Array.from({ length: 256 }, (v, i) => (i + 256).toString(16).slice(1));
function fID(arr, o = 0) { const id = (hT[arr[o]] + hT[arr[o + 1]] + hT[arr[o + 2]] + hT[arr[o + 3]] + "-" + hT[arr[o + 4]] + hT[arr[o + 5]] + "-" + hT[arr[o + 6]] + hT[arr[o + 7]] + "-" + hT[arr[o + 8]] + hT[arr[o + 9]] + "-" + hT[arr[o + 10]] + hT[arr[o + 11]] + hT[arr[o + 12]] + hT[arr[o + 13]] + hT[arr[o + 14]] + hT[arr[o + 15]]).toLowerCase(); if (!isVF(id)) throw new TypeError(E8); return id; }
